# Generated by Django 3.1 on 2020-08-26 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default_user_avatar.png', upload_to='avatars/')),
                ('open_cases', models.IntegerField(default=0, verbose_name='Кол-во открытых кейсов')),
                ('spent_money', models.IntegerField(default=0, verbose_name='Кол-во потраченых денег')),
                ('balance', models.IntegerField(default=1000, verbose_name='Баланс')),
                ('entered_money', models.IntegerField(default=0, verbose_name='Введено денег')),
                ('withdraw_money', models.IntegerField(default=0, verbose_name='Выведено денег')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('admin_mode', models.BooleanField(default=False, verbose_name='Админ мод')),
                ('is_connection', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('quantity_connections', models.IntegerField(default=1, verbose_name='Количество открытых подключений')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
